spring:
  datasource:
    url: jdbc:mysql://47.94.238.122/youcai?useSSL=false
    password: qing1016..
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /guest
security:
  basic:
    enabled: false
