spring:
  datasource:
    url: jdbc:mysql:///youcai?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    password: qing1016..
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd
    time-zone: GMT+8
server:
  context-path: /guest
  port: 8060
security:
  basic:
    enabled: false
