spring:
  datasource:
  #    url: jdbc:mysql://47.94.238.122/youcai?useSSL=false
    url: jdbc:mysql:///youcai?useSSL=false
    password: qing1016..
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /guest
  port: 8060
security:
  basic:
    enabled: false
